/**
 * Nigerian universities (federal, state, and private) offered when a host
 * opens a space, so we can count how many students sign out per university.
 * Like banks.ts, we store the university *name* on the space (not a code), so
 * display and aggregation don't depend on this list staying in sync — the
 * array just drives the create-form dropdown. Keep it alphabetised so the
 * native select's type-ahead works; "Other university" is the catch-all.
 */
export const NIGERIAN_UNIVERSITIES: string[] = [
	"Abdulkadir Kure University",
	"Abia State University",
	"Abiola Ajimobi Technical University (First Technical University)",
	"Abubakar Tafawa Balewa University",
	"Achievers University",
	"Adamawa State University",
	"Adekunle Ajasin University",
	"Adeleke University",
	"Adeyemi Federal University of Education",
	"Admiralty University of Nigeria",
	"Afe Babalola University (ABUAD)",
	"African University of Science and Technology",
	"Ahmadu Bello University (ABU)",
	"Ahman Pategi University",
	"Air Force Institute of Technology",
	"Ajayi Crowther University",
	"Akwa Ibom State University",
	"Al-Ansar University, Maiduguri",
	"Al-Hikmah University",
	"Al-Istiqama University, Sumaila",
	"Al-Qalam University, Katsina",
	"Alex Ekwueme Federal University, Ndufu-Alike",
	"Aliko Dangote University of Science and Technology, Wudil",
	"Alvan Ikoku Federal University of Education",
	"Ambrose Alli University",
	"American University of Nigeria",
	"Anchor University",
	"Arthur Jarvis University",
	"Atiba University",
	"Augustine University",
	"Ave Maria University",
	"Babcock University",
	"Bamidele Olumilua University of Education, Science and Technology",
	"Bauchi State University",
	"Bayelsa Medical University",
	"Bayero University, Kano (BUK)",
	"Baze University",
	"Bells University of Technology",
	"Benson Idahosa University",
	"Benue State University",
	"Bingham University",
	"Borno State University",
	"Bowen University",
	"Caleb University",
	"Capital City University, Kano",
	"Caritas University",
	"CETEP City University",
	"Chrisland University",
	"Christopher University",
	"Chukwuemeka Odumegwu Ojukwu University",
	"Claretian University of Nigeria",
	"Clifford University",
	"Coal City University",
	"Confluence University of Science and Technology, Osara",
	"Covenant University",
	"Crawford University",
	"Crescent University",
	"David Umahi Federal University of Health Sciences",
	"Delta State University, Abraka (DELSU)",
	"Delta State University of Science and Technology, Ozoro",
	"Dennis Osadebay University",
	"Dominican University, Ibadan",
	"Dominion University",
	"Ebonyi State University",
	"Edo State University, Uzairue",
	"Edwin Clark University",
	"Ekiti State University (EKSU)",
	"Elizade University",
	"Emmanuel Alayande University of Education",
	"Enugu State University of Science and Technology (ESUT)",
	"Evangel University, Akaeze",
	"Federal University, Birnin Kebbi",
	"Federal University, Dutse",
	"Federal University, Dutsin-Ma",
	"Federal University, Gashua",
	"Federal University, Gusau",
	"Federal University, Kashere",
	"Federal University, Lafia",
	"Federal University, Lokoja",
	"Federal University, Otuoke",
	"Federal University, Oye-Ekiti",
	"Federal University, Wukari",
	"Federal University of Agriculture, Abeokuta (FUNAAB)",
	"Federal University of Agriculture, Mubi",
	"Federal University of Agriculture, Zuru",
	"Federal University of Applied Sciences, Kachia",
	"Federal University of Education, Pankshin",
	"Federal University of Education, Zaria",
	"Federal University of Health Sciences, Azare",
	"Federal University of Health Sciences, Ila-Orangun",
	"Federal University of Health Sciences, Otukpo",
	"Federal University of Petroleum Resources, Effurun (FUPRE)",
	"Federal University of Technology, Akure (FUTA)",
	"Federal University of Technology, Minna (FUTMINNA)",
	"Federal University of Technology, Owerri (FUTO)",
	"Federal University of Transportation, Daura",
	"Fountain University",
	"Godfrey Okoye University",
	"Gombe State University",
	"Gombe State University of Science and Technology",
	"Greenfield University",
	"Gregory University",
	"Hallmark University",
	"Hezekiah University",
	"Ibrahim Badamasi Babangida University",
	"Igbinedion University",
	"Ignatius Ajuru University of Education",
	"Imo State University",
	"James Hope University",
	"Joseph Ayo Babalola University",
	"Joseph Sarwuan Tarka University, Makurdi",
	"Kaduna State University",
	"Kebbi State University of Science and Technology",
	"Khadija University",
	"Kings University",
	"Kingsley Ozumba Mbadiwe University",
	"KolaDaisi University",
	"Kwara State University (KWASU)",
	"Kwararafa University",
	"Ladoke Akintola University of Technology (LAUTECH)",
	"Lagos State University (LASU)",
	"Lagos State University of Education",
	"Lagos State University of Science and Technology",
	"Landmark University",
	"Lead City University",
	"Legacy University, Okija",
	"Madonna University",
	"Maryam Abacha American University of Nigeria",
	"McPherson University",
	"Mewar International University",
	"Michael and Cecilia Ibru University",
	"Michael Okpara University of Agriculture, Umudike",
	"Miva Open University",
	"Modibbo Adama University, Yola",
	"Moshood Abiola University of Science and Technology, Abeokuta",
	"Mountain Top University",
	"Mudiame University",
	"Nasarawa State University",
	"National Open University of Nigeria (NOUN)",
	"Niger Delta University",
	"Nigeria Police Academy, Wudil",
	"Nigerian Army University, Biu",
	"Nigerian Defence Academy",
	"Nigerian Maritime University",
	"Nigerian University of Technology and Management",
	"Nile University of Nigeria",
	"Nnamdi Azikiwe University (UNIZIK)",
	"Nok University, Kachia",
	"Novena University",
	"Obafemi Awolowo University (OAU)",
	"Obong University",
	"Oduduwa University",
	"Olabisi Onabanjo University (OOU)",
	"Olusegun Agagu University of Science and Technology",
	"Osun State University (UNIOSUN)",
	"PAMO University of Medical Sciences",
	"Pan-Atlantic University",
	"Paul University",
	"Peaceland University",
	"Plateau State University",
	"Precious Cornerstone University",
	"Prince Abubakar Audu University",
	"Redeemer's University",
	"Renaissance University",
	"Rhema University",
	"Ritman University",
	"Rivers State University",
	"Salem University",
	"Sam Maris University",
	"Samuel Adegboyega University",
	"Shehu Shagari University of Education, Sokoto",
	"Skyline University Nigeria",
	"Sokoto State University",
	"Spiritan University, Nneochi",
	"Sule Lamido University",
	"Summit University",
	"Tai Solarin University of Education (TASUED)",
	"Taraba State University",
	"Thomas Adewumi University",
	"Topfaith University",
	"Trinity University",
	"Umaru Musa Yar'adua University",
	"University of Abuja (UNIABUJA)",
	"University of Benin (UNIBEN)",
	"University of Calabar (UNICAL)",
	"University of Cross River State",
	"University of Delta",
	"University of Ibadan (UI)",
	"University of Ilorin (UNILORIN)",
	"University of Jos (UNIJOS)",
	"University of Lagos (UNILAG)",
	"University of Maiduguri (UNIMAID)",
	"University of Medical Sciences, Ondo (UNIMED)",
	"University of Mkar",
	"University of Nigeria, Nsukka (UNN)",
	"University of Port Harcourt (UNIPORT)",
	"University of Uyo (UNIUYO)",
	"Usmanu Danfodiyo University, Sokoto (UDUS)",
	"Veritas University",
	"Wellspring University",
	"Wesley University",
	"Western Delta University",
	"Westland University",
	"Yobe State University",
	"Yusuf Maitama Sule Federal University of Education, Kano",
	"Yusuf Maitama Sule University, Kano",
	"Zamfara State University",
	"Other university",
];
